import { Press_Start_2P } from 'next/font/google'
import { Share_Tech } from 'next/font/google';
import "./globals.css";

const pressStart2P = Press_Start_2P({
  subsets: ['latin'],
  weight: '400',
})

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
